version: "3.2"
services:
  mongodb:
    image: mongo:4.4.1-bionic
    container_name: "mongodb"
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=project
    volumes:
      - ./data/db_prod:/data/db
    ports:
      - 27017:27017
  service:
    build: .
    container_name: blogService
    restart: always
    environment:
      - APP_PORT=3000
      - MONGO_URL=mongodb://admin:password@mongodb:27017/app?authSource=admin
    ports:
      - 3000:3000
    links:
      - mongodb
