version: "3.2"
services:
  mongodb:
    image: mongo:4.4.1-bionic
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=project
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

