basePath: /
definitions:
    IBlog:
        description: ""
        properties:
            _id:
                type: string
                description: ""
            author:
                type: string
                description: ""
            date:
                type: string
                format: date-time
                description: ""
            commentIds:
                type: array
                items:
                    type: string
                description: ""
            title:
                type: string
                description: ""
            content:
                type: string
                description: ""
        type: object
        required:
            - author
            - date
            - commentIds
            - title
            - content
    BlogCreator:
        description: ""
        properties:
            title:
                type: string
                description: ""
            content:
                type: string
                description: ""
        type: object
        required:
            - title
            - content
    BlogUpdater:
        description: ""
        properties:
            title:
                type: string
                description: ""
            content:
                type: string
                description: ""
        type: object
    IComment:
        description: ""
        properties:
            _id:
                type: string
                description: ""
            author:
                type: string
                description: ""
            message:
                type: string
                description: ""
            date:
                type: string
                format: date-time
                description: ""
        type: object
        required:
            - author
            - message
            - date
    CommentCreator:
        description: ""
        properties:
            message:
                type: string
                description: ""
        type: object
        required:
            - message
info:
    description: 'Simple blog REST API'
    license:
        name: MIT
    title: Blog
    version: 1.0.0
paths:
    /blog:
        post:
            operationId: BlogServiceCreate
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        $ref: '#/definitions/IBlog'
            description: ""
            security:
                -
                    default:
                        - basicAuth
            consumes:
                - application/json
            parameters:
                -
                    description: ""
                    in: body
                    name: blog
                    required: true
                    schema:
                        $ref: '#/definitions/BlogCreator'
        get:
            operationId: BlogServiceList
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/IBlog'
            description: ""
            parameters: []
    '/blog/{id}':
        put:
            operationId: BlogServiceUpdate
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        $ref: '#/definitions/IBlog'
            description: ""
            security:
                -
                    default:
                        - basicAuth
            consumes:
                - application/json
            parameters:
                -
                    description: ""
                    in: body
                    name: blog
                    required: true
                    schema:
                        $ref: '#/definitions/BlogUpdater'
                -
                    description: ""
                    in: path
                    name: id
                    required: true
                    type: string
        delete:
            operationId: BlogServiceDelete
            produces:
                - text/html
            responses:
                '204':
                    description: 'No content'
            description: ""
            security:
                -
                    default:
                        - basicAuth
            parameters:
                -
                    description: ""
                    in: path
                    name: id
                    required: true
                    type: string
    '/blog/{blogId}/comment':
        post:
            operationId: CommentServiceCreate
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        $ref: '#/definitions/IComment'
            description: ""
            security:
                -
                    default:
                        - basicAuth
            consumes:
                - application/json
            parameters:
                -
                    description: ""
                    in: body
                    name: commentCreator
                    required: true
                    schema:
                        $ref: '#/definitions/CommentCreator'
                -
                    description: ""
                    in: path
                    name: blogId
                    required: true
                    type: string
swagger: '2.0'
securityDefinitions:
    basicAuth:
        type: basic
host: 'localhost:3000'
